### ISSUE TITLE
JPHP "Hello World" example doesn't run after JPPM 6.0.1 installation

### ISSUE THREAD

**Issue by AryToNeX** [jphp-group/jphp#376]
```
naomi@naomi-laptop:~/test$ jppm app:run
-> linux
-> app:run 
-> install 
java.lang.IllegalArgumentException
        at org.objectweb.asm.FieldVisitor.<init>(Unknown Source)
        at org.objectweb.asm.FieldVisitor.<init>(Unknown Source)
        at org.objectweb.asm.tree.FieldNode.<init>(FieldNode.java:129)
        at org.objectweb.asm.tree.FieldNode.<init>(FieldNode.java:102)
        at org.develnext.jphp.core.compiler.jvm.statement.ClassStmtCompiler.writeSystemInfo(ClassStmtCompiler.java:468)
        at org.develnext.jphp.core.compiler.jvm.statement.ClassStmtCompiler.compile(ClassStmtCompiler.java:1176)
        at org.develnext.jphp.core.compiler.jvm.JvmCompiler.compile(JvmCompiler.java:280)
        at php.runtime.env.Environment.importModule(Environment.java:1246)
        at php.runtime.env.ConcurrentEnvironment.importModule(ConcurrentEnvironment.java:175)
        at php.runtime.env.ModuleManager.fetchTemporaryModule(ModuleManager.java:71)
        at php.runtime.env.ModuleManager.fetchModule(ModuleManager.java:41)
        at php.runtime.env.ModuleManager.fetchModule(ModuleManager.java:27)
        at php.runtime.launcher.Launcher.loadFrom(Launcher.java:121)
        at php.runtime.launcher.Launcher.run(Launcher.java:308)
        at php.runtime.launcher.Launcher.run(Launcher.java:247)
        at php.runtime.launcher.Launcher.run(Launcher.java:243)
        at php.runtime.launcher.Launcher.main(Launcher.java:425)
```

```
naomi@naomi-laptop:~/test$ jppm version
-> linux
JPPM Information:
-> version: 0.6.1
--> jphp: 1.0.3
--> java: 1.8.0_242 (amd64)
-> home: '/opt/jppm-0.6.1'
--> java home: '/usr/lib/jvm/java-8-openjdk-amd64'
```

**Comment by dim-s** [comment]
Try to delete `vendor` folder in your project dir.

**Comment by dim-s** [comment]
It was a bug not related to jppm, the problem was in extra jar files of the asm library in the jphp-core.

To fix run `jppm update`, this command updates all dependencies in your project.
