### ISSUE TITLE
Failure while parsing particularly large files

### ISSUE THREAD

**Issue by danog** [jphp-group/jphp#393]
Crash while parsing particularly large files, like for example https://github.com/amphp/hpack/blob/master/src/Internal/huffman-lookup.php

PHP is capable of parsing the file just fine.

Result:
```
[daniil@daniil-arch jav]$ jppm start
-> linux
-> app:run 
-> install 
org.objectweb.asm.MethodTooLargeException: Method too large: $php_module_m3cdaffad1d624e84a03b74e4ae5f0c22.__include (Lphp/runtime/env/Environment;[Lphp/runtime/Memory;Lphp/runtime/memory/ArrayMemory;)Lphp/runtime/Memory;
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:489)
        at org.develnext.jphp.core.compiler.jvm.statement.ClassStmtCompiler.compile(ClassStmtCompiler.java:1229)
        at org.develnext.jphp.core.compiler.jvm.JvmCompiler.compile(JvmCompiler.java:281)
        at php.runtime.env.Environment.importModule(Environment.java:1251)
        at php.runtime.env.ConcurrentEnvironment.importModule(ConcurrentEnvironment.java:175)
        at php.runtime.env.ModuleManager.fetchTemporaryModule(ModuleManager.java:71)
        at php.runtime.env.ModuleManager.fetchModule(ModuleManager.java:41)
        at php.runtime.env.ModuleManager.fetchModule(ModuleManager.java:27)
        at php.runtime.launcher.Launcher.loadFrom(Launcher.java:121)
        at php.runtime.launcher.Launcher.run(Launcher.java:308)
        at php.runtime.launcher.Launcher.run(Launcher.java:247)
        at php.runtime.launcher.Launcher.run(Launcher.java:243)
        at php.runtime.launcher.Launcher.main(Launcher.java:425)
```

**Comment by dim-s** [comment]
This problem cannot be fixed because this is a limitation of the JVM, for example, the same limitation exists in the Java language and other jvm languages, you cannot create a very large method with a large number of lines of code.

**Comment by danog** [comment]
Understandable, I'll find a workaround.
